# Импорт библиотеки NumPy с общепринятым сокращением. Создание массивов разными способами

In [1]:
import numpy as np

list_array = np.array([1, 2, 3, 4, 5])
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((3, 2))
range_arr = np.arange(0, 15, 3)

print("Созданные массивы:")
print("Из списка:", list_array)
print("2D массив:\n", matrix_2d)
print("Нулевой массив:\n", zeros_arr)
print("Массив единиц:\n", ones_arr)
print("Массив с arange:", range_arr)
print()

Созданные массивы:
Из списка: [1 2 3 4 5]
2D массив:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Нулевой массив:
 [[0. 0. 0.]
 [0. 0. 0.]]
Массив единиц:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Массив с arange: [ 0  3  6  9 12]



# Демонстрация атрибутов массива

In [2]:
print("Атрибуты 2D массива:")
print("Форма:", matrix_2d.shape)
print("Тип данных:", matrix_2d.dtype)
print("Размерность:", matrix_2d.ndim)
print("Всего элементов:", matrix_2d.size)
print()

Атрибуты 2D массива:
Форма: (3, 3)
Тип данных: int32
Размерность: 2
Всего элементов: 9



# Индексирование и срезы

In [3]:
test_data = np.array([[10, 20, 30, 40], 
                      [50, 60, 70, 80], 
                      [90, 100, 110, 120]])

print("Тестовый массив:")
print(test_data)

single_element = test_data[1, 2]
row_slice = test_data[0, :]
column_slice = test_data[:, 1]
sub_matrix = test_data[1:3, 1:4]

print("\nРезультаты индексирования:")
print("Отдельный элемент [1,2]:", single_element)
print("Первая строка:", row_slice)
print("Второй столбец:", column_slice)
print("Подмассив 2x3:\n", sub_matrix)
print()

Тестовый массив:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Результаты индексирования:
Отдельный элемент [1,2]: 70
Первая строка: [10 20 30 40]
Второй столбец: [ 20  60 100]
Подмассив 2x3:
 [[ 60  70  80]
 [100 110 120]]



# Векторные операции и статистика

In [4]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

elementwise_sum = arr1 + arr2
elementwise_product = arr1 * arr2
scalar_multiply = arr1 * 3

print("Векторные операции:")
print("Массив 1:", arr1)
print("Массив 2:", arr2)
print("Поэлементная сумма:", elementwise_sum)
print("Поэлементное умножение:", elementwise_product)
print("Умножение на скаляр (3):", scalar_multiply)
print()

Векторные операции:
Массив 1: [1 2 3 4]
Массив 2: [5 6 7 8]
Поэлементная сумма: [ 6  8 10 12]
Поэлементное умножение: [ 5 12 21 32]
Умножение на скаляр (3): [ 3  6  9 12]



# Базовая статистика

In [5]:
stats_array = np.array([2, 5, 8, 1, 9, 3, 7, 4, 6])

mean_value = np.mean(stats_array)
max_value = np.max(stats_array)
min_value = np.min(stats_array)
sum_value = np.sum(stats_array)

print("Статистика по массиву:", stats_array)
print("Среднее значение:", mean_value)
print("Максимальное значение:", max_value)
print("Минимальное значение:", min_value)
print("Сумма всех элементов:", sum_value)

Статистика по массиву: [2 5 8 1 9 3 7 4 6]
Среднее значение: 5.0
Максимальное значение: 9
Минимальное значение: 1
Сумма всех элементов: 45
